"""empty message

Revision ID: 4c04e991e03f
Revises: 
Create Date: 2026-03-11 12:29:56.482304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c04e991e03f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slide_templates')
    op.drop_table('presentations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentations',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('json_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reference_text', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('slides_count', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('plans', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('presentations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('presentations_pkey'))
    )
    op.create_table('slide_templates',
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('template_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('slides_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('ratio', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('color_scheme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('badge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('slide_templates_pkey'))
    )
    # ### end Alembic commands ###
