"""empty message

Revision ID: 1df83151c821
Revises: 2a20238d5b78
Create Date: 2026-03-20 17:41:09.948541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df83151c821'
down_revision: Union[str, None] = '2a20238d5b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_templates',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('template_path', sa.String(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('slides_count', sa.SmallInteger(), nullable=False),
    sa.Column('ratio', sa.String(length=5), nullable=False),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('file_size', sa.String(length=10), nullable=False),
    sa.Column('color_scheme', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slide_templates')
    # ### end Alembic commands ###
