"""empty message

Revision ID: 4181fa42b2f7
Revises: 85b243239069
Create Date: 2026-03-04 16:08:12.601713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4181fa42b2f7'
down_revision: Union[str, None] = '85b243239069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.drop_table('slide_templates')
    op.drop_column('presentations', 'recipient')
    op.drop_column('presentations', 'slides_count')
    op.drop_column('presentations', 'plans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('plans', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('presentations', sa.Column('slides_count', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('presentations', sa.Column('recipient', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('slide_templates',
    sa.Column('images', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False),
    sa.Column('slides_count', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('ratio', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('color_scheme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('badge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('template_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='slide_templates_pkey')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###
