"""empty message

Revision ID: 99501df9d20e
Revises: 1df83151c821
Create Date: 2026-03-20 19:16:59.060003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99501df9d20e'
down_revision: Union[str, None] = '1df83151c821'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('presentations', sa.Column('recipient', sa.String(), nullable=True))
    op.add_column('presentations', sa.Column('slides_count', sa.SmallInteger(), nullable=True))
    op.add_column('presentations', sa.Column('plans', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('presentations', 'plans')
    op.drop_column('presentations', 'slides_count')
    op.drop_column('presentations', 'recipient')
    # ### end Alembic commands ###
